node_js:
- "4"
- "6"
- "7"
language: node_js
env: DEBUG=zombie
install:
- npm install
- npm install -g codecov istanbul
script:
- npm test
- istanbul cover ./node_modules/.bin/mocha --report lcovonly -- -R spec
- codecov
